before_script:
  - yarn

stages:
  - build
  - deploy

cache:
  untracked: true
  paths:
    - node_modules/

Build:
  stage: build
  only:
    - master
  script:
    - CI="" yarn build
  artifacts:
    paths:
    - build/

Deploy:
  stage: deploy
  only:
    - master
  before_script:
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/atoms/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/atoms/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/cells/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/cells/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/molecules/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/molecules/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/theme/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/theme/package.json"
    - "sed -i \"s|\\\"main\\\": \\\"src|\\\"main\\\": \\\"build|g\" packages/utils/package.json"
    - "sed -i \"s|\\\"module\\\": \\\"src|\\\"module\\\": \\\"build|g\" packages/utils/package.json"
  script:
    - yarn make-oao-nexus
